AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patientcheckout

  Sample SAM Template for patientcheckout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 20
    Environment:
      Variables:
        PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic

Resources:
  PatientCheckoutDLQ:
    Type: AWS::SNS::Topic

  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

  PatientCheckoutTopic:
    Type: AWS::SNS::Topic

  PatientCheckoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.autobots.aws.lambda.s3sns.PatientCheckoutFunction::handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Events:
        S3PatienCheckoutEvent:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
  
  BillManagementFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.autobots.aws.lambda.s3sns.BillManagementFunction::handler
      Events:
        SNSBillManagementEvent:
          Type: SNS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Topic: !Ref PatientCheckoutTopic
    
    
