version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "firstSnapStartLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nseg5wsp1f34"
s3_prefix = "firstSnapStartLambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
